#ifndef PWRINSPACE_CAN_COMMANDS_H
#define PWRINSPACE_CAN_COMMANDS_H

/** PLACE YOUR CAN CALLBACKS AND CAN MESSAGES HERE IN FORMAT*/
typedef enum {
    //RECIEVE COMMANDS
    CAN_GET_STATUS = 0x3CF,
    CAN_GET_BOARD_DATA = 0x2CE,
    CAN_OPEN_SOLENOID = 0x0CD,
    CAN_CLOSE_SOLENOID = 0x0CC,
    CAN_OPEN_SERVO = 0x0CB,
    CAN_CLOSE_SERVO = 0x0CA,
    CAN_MOVE_SERVO = 0x0C9,
    RESET = 0x0C0,
    //SEND COMMANDS
    CAN_SEND_STATUS = 0x3CD,
    CAN_SEND_BOARD_DATA = 0x3C0

} can_message_id_t;

/*PLACE YOUR FUNCTIONS ACCORDING TO THE TEMPLATE
* typedef esp_err_t (*can_command_handler_t)(uint8_t *data, uint8_t length);
* 
* REGISTER THEM IN can_config.c FILE
*/




#endif //PWRINSPACE_CAN_COMMANDS_H