#ifndef PWRINSPACE_CAN_COMMANDS_H
#define PWRINSPACE_CAN_COMMANDS_H

/** PLACE YOUR CAN CALLBACKS AND CAN MESSAGES HERE IN FORMAT*/
typedef enum {
    //RECIEVE COMMANDS
    CAN_GET_STATUS = 0x3CF0,
    CAN_GET_BOARD_DATA = 0x2CE0,
    CAN_OPEN_SOLENOID = 0x0CD0,
    CAN_CLOSE_SOLENOID = 0x0CC0,
    CAN_OPEN_SERVO = 0x0CB0,
    CAN_CLOSE_SERVO = 0x0CA0,
    CAN_MOVE_SERVO = 0x0C90,
    RESET = 0x0C00,
    //SEND COMMANDS
    CAN_SEND_STATUS = 0x3CD0,
    CAN_SEND_BOARD_DATA = 0x3C00

} can_message_id_t;

/*PLACE YOUR FUNCTIONS ACCORDING TO THE TEMPLATE
* typedef esp_err_t (*can_command_handler_t)(uint8_t *data, uint8_t length);
* 
* REGISTER THEM IN can_config.c FILE
*/




#endif //PWRINSPACE_CAN_COMMANDS_H